Repository spacetelescope/stistools, pull requests merged in 2025-01, with the labels that each got.

#171 Cleaning up test infrastructure
  pyproject.toml
  tests/conftest.py
  tests/helpers/io.py
  tests/helpers/utils.py
  tests/resources.py
Labels: testing

#136 Updated link to STIS DHB [ci skip]
  doc/source/index.rst
Labels: docs

#172 Repair RTD
  .readthedocs.yaml
  doc/source/conf.py
  pyproject.toml
  stistools/ctestis.py
  stistools/evaldisp.py
  stistools/gettable.py
  stistools/r_util.py
  stistools/radialvel.py
  stistools/sshift.py
  stistools/stisnoise.py
  stistools/wavelen.py
  stistools/wx2d.py
Labels: docs

#169 New routine: ocrreject_exam()
  doc/source/index.rst
  doc/source/ocrreject_exam.rst
  doc/source/odvkl1040_splits.png
  doc/source/odvkl1040_stacked.png
  pyproject.toml
  stistools/__init__.py
  stistools/ocrreject_exam.py
  tests/test_ocrreject_exam.py
Labels: enhancement
